### ISSUE TITLE
Calculate coefficients of MILP objective for reversible reactions

### ISSUE THREAD

**Issue by hvdinh16** [shyamsrinivasan/mfa_design#1]
There are three choices for these:
1) (currently implemented) Take difference of absolute flux values for two mutants
sqrt[ sum[ abs(v1_j) - abs(v2_j) ]^2 ]
2) Difference of flux values for two mutants
sqrt[ sum[ v1_j - v2_j ]^2 ]
3) Split to two reactions and consider them separately, thus there are two separate term in the sum:
abs(v1_j_fwd) - abs(v2_j_fwd)
abs(v1_j_rev) - abs(v2_j_rev)

**Comment by shyamsrinivasan** [comment]
This becomes valid only if forward and reverse components of a reaction are catalyzed by separate enzymes, and the individual flux of each of the two components can be measured. From what I understand of the currently available flux datasets that we have in our possession, this should not be an issue. So, I am closing this issue.
