### ISSUE TITLE
ATP synthase knockout in aerobic condition

### ISSUE THREAD

**Issue by hvdinh16** [shyamsrinivasan/mfa_design#2]
Might have to notice ATP synthase KO in aerobic condition. For implementation on E. coli core model, the model switch to acetate and formate fermentation. Having pseudo-anaerobic flux distribution is dangerous when determine kinetic parameters for aerobic condition (https://www.nature.com/articles/ncomms13806).

**Comment by shyamsrinivasan** [comment]
This reaction will typically kill the cell, or at least result in a considerable burden. So, this reaction should never be included in the list of typical KOs
